<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
 <modelVersion>4.0.0</modelVersion>
 <groupId>rs.ac.bg.matf.oop</groupId><artifactId>nedelja11</artifactId><version>1.0</version>
 <properties>
  <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding><maven.compiler.release>21</maven.compiler.release>
  <javafx.mainClass>primer05_zavrsna_aplikacija.prikaz.PlanerAplikacija</javafx.mainClass>
 </properties>
 
 <build>
  <sourceDirectory>src</sourceDirectory><testSourceDirectory>test</testSourceDirectory>
  <plugins>
   <plugin><groupId>org.apache.maven.plugins</groupId><artifactId>maven-compiler-plugin</artifactId><version>3.13.0</version></plugin>
   <plugin><groupId>org.codehaus.mojo</groupId><artifactId>exec-maven-plugin</artifactId><version>3.1.0</version>
    <executions><execution><id>provera-materijala</id><phase>verify</phase><goals><goal>java</goal></goals>
     <configuration><mainClass>provere.Main</mainClass><classpathScope>test</classpathScope></configuration>
    </execution></executions>
   </plugin>
   
  </plugins>
 </build>
</project>
